-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.responses
(
    id serial NOT NULL,
    session_id integer NOT NULL,
    message_id integer NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT responses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    id serial NOT NULL,
    session_id integer NOT NULL,
    role character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'user'::character varying,
    content character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone,
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_sessions
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone,
    CONSTRAINT chat_sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying COLLATE pg_catalog."default" NOT NULL,
    hashed_password character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.persistent_storage
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT persistent_storage_pkey PRIMARY KEY (id),
    CONSTRAINT persistent_storage_user_id_key_key UNIQUE (user_id, key)
);

CREATE TABLE IF NOT EXISTS public.temporary_storage
(
    id serial NOT NULL,
    session_id integer NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT temporary_storage_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.responses
    ADD CONSTRAINT responses_message_id_fkey FOREIGN KEY (message_id)
    REFERENCES public.messages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.responses
    ADD CONSTRAINT responses_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.chat_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.chat_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.chat_sessions
    ADD CONSTRAINT chat_sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.persistent_storage
    ADD CONSTRAINT persistent_storage_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.temporary_storage
    ADD CONSTRAINT temporary_storage_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.chat_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;